### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by the-c0d3br34k3r** [the-c0d3br34k3r/docker_images#2]
Provide the following details in the README:
> List of docker vms
> Commands to download and run a docker container.

**Comment by aditya274** [comment]
Hello, I am trying to make my very first pull request. I would be glad if you assign me.

**Comment by the-c0d3br34k3r** [comment]
Hey Aditya,
Thank you for your interest!
I've assigned it to you. The goal of this issue is to create a README.md for this repository and add the following info:

**Available Docker images**
- **Authentication Servers**
    - **FreeRadius**
Username: testuser, 
Password: password, 
Supported Auth-Types: PAP, CHAP, MSCHAP, or EAP-MD5


**Instructions to deploy a Docker image**
1. Clone the repository.
`$ git clone git@github.com:the-c0d3br34k3r/docker_images.git`
2. Ensure that you have Docker installed.
    ```
    $ docker -v
    Docker version 18.09.7, build 2d0083d
    ```
3. Navigate to the desired docker image folder. 
`$ cd <DOCKER_IMAGE_FOLDER>`
4. Ensure that the current directory you're in contains a Dockerfile.
    ```
    $ ls 
    ...
    Dockerfile
    ...
    ```
5. Build the image from the Dockerfile. Provide a tag name that is relevant to the image being used. For example, if you're using the FreeRADIUS docker image, `freeradius` would be a suitable tag.
    `$ docker image build . -t <TAG>`
6. Run the built docker image.
    `$ docker run -it <TAG>`
7. Run the desired service:
    **For FreeRADIUS:**
    `root@<CONTAINER_ID>:/# freeradius -X`
8. Refer the **test.txt** file within the docker image folder for instructions on how to test the service.
